#!/usr/bin/env sh


rm -rf metrics
mkdir metrics
# HTML
for i in $(ls templates/*.html)
do
htmlmin $i >> metrics/html
done

echo "HTML" `cat metrics/html | gzip | wc -c`

# Python
pyminifier kiloblog.py | head -n -2 > metrics/kiloblog.py

echo "Python" `cat metrics/kiloblog.py | gzip | wc -c`

# JavaScript
# CSS

rm -rf metrics
